#!/usr/bin/env bash
# Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

counter=0
while [ $counter -lt 10 ]
do
    if [ $counter = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter+=1))
done
