#!/usr/bin/env bash
# a Bash script that loops from 1 to 20 and print some statment

i=1
while [ $i -le 20 ]
do
    case $i in
                4 )
                echo "$i"
                echo "bad luck from China" ;;
                9 )
                echo "$i"
                echo "bad luck from Japan" ;;
                17 )
                echo "$i"
                echo "bad luck from Italy" ;;
                * )
                echo "$i" ;;
            esac
((i++))
done
